### PR TITLE
exercise and solution nb 16

### LINKED ISSUE #49: Add exercises and solutions to 16 Performance metrics and Model Evaluation

### PR DESCRIPTION
**Pull request by rasbt**
fixes #49

### CODE REVIEW

**Comment by rasbt** [comment]
arg I forgot to save the notebook after I cleared the output, wait a sec

**Comment by amueller** [comment]
great idea. Clear the cells?

**Comment by rasbt** [comment]
should be fine now

**Comment by amueller** [comment]
hm maybe use accuracy score from metrics instead of reimplementing it in the solution? but no strong opinion. feel free to merge.

**Comment by rasbt** [comment]
Yeah, I think people will do that automatically. Just thought it was useful to do it explicitely to be able to look at the difference between this accuracy computation and macro wrapper?

**Pull request merged**
