### PR TITLE
nb01.x: various typo fixes / 2.7 compatibility fixes

### PR DESCRIPTION
**Pull request by nelson-liu**
made some typo fixes for nbs 01.x, and also made the stratified split example in nb01.4 compatible with Python 2.x

### CODE REVIEW

**Comment by nelson-liu** [comment]
(I've never really worked with ipython notebooks in git before, so let me know if there's anything I'm doing wrong in terms of changing things. The large diffs for small changes make me feel a bit uneasy.)

**Comment by rasbt** [comment]
That's really nice of you, thanks! One little thing though, could you please  clear the output cells in the notebooks (because the attendees are supposed to execute the code themselves) and rebase (squash) your commit to make the diffs a bit easier on us? Thanks anyway, as far as I can tell, these are some useful fixes!

**Comment by nelson-liu** [comment]
done, lmk if that is ok. i noticed that the image explaining the basics of ML doesn't show up on the github preview of the notebook, is this intended or is it an "output"?

**Comment by rasbt** [comment]
The fixes look good to me, thanks! About the image; hm, not really intentional, but I think this may be because GitHub doesn't render SVGs in Jupyter notebooks yet? Locally, it works fine though, right? I wouldn't necessarily convert the image just because of GitHub rendering.

**Pull request merged**
