### PR TITLE
Rearrange outline

### PR DESCRIPTION
**Pull request by amueller**
this numbers all the topics and rearranges them a bit.
I'm not sure about having separate notebooks for 05 and 06.
I'm also not sure what you had in mind for 07. A general overview that is made more concrete in 08 and 09?

We don't have notebooks for 24-28 right now, and I don't have a good feeling for what the idea was with 17.

### CODE REVIEW

**Comment by rasbt** [comment]
Looks good now. I see that you added the Linear Models section already; and you removed the nested CV section. I can append a section to the Cross-Validation section on nested CV.
- Notebook 17? Hm, no idea, I think that it is/could be sort of covered in 16.
- 24 Supervised learning: Non-linear regression analysis: I think there was some decision tree regression somewhere at least. Maybe pulling it from there and adding SVM regression?
- 25: Unsupervised learning: Hierarchical and density-based clustering algorithms: I could do that
- 26 Unsupervised learning: Non-linear dimensionality reduction: I there was a brief manifold learning/isomap example in the very beginning (I think in the unsupervised transformers); maybe you could pull it from there and extend it a bit?
- 27 Wrapper, filter, and embedded approaches for feature selection: Are you working on that?
- 28 Supervised learning: Out-of-core learning; I could do this one using IMDb

So, let me do 25 & 28 if you don't mind (will start tonight). Plus, I will send you the slides after the readjustements on Sat/Sun.

**Comment by amueller** [comment]
The nested CV was mostly at a very odd place, I thought, between SVM and Trees.

**Comment by amueller** [comment]
I haven't started working on anything lol. Sorry.
For 24: We could either explain regression when explaining the models directly (they are mostly the same for classification and regression) or we could make 24 "regression works just like classfication" ^^

**Comment by amueller** [comment]
I can do 27 and 26 and I'll go over everything again.

**Comment by amueller** [comment]
merge?

**Comment by rasbt** [comment]
> I haven't started working on anything lol. Sorry.

Haha, lol, yeah, but I am sure everything will come together nicely. Our tutorial is Tue, so plenty of time on the weekend. Haha, my boss was pressuring me to submit a research paper before I go to Texas ... which kept me mostly busy but I will submit it in a few hours so that's off my plate and I only have to worry about scipy then I guess :)

> I can do 27 and 26 and I'll go over everything again.

That'll be great, thanks! I'll do 25 & 28 then!

+1 on merging

**Pull request merged**
