### PR TITLE
add gridsearch exercise

### PR DESCRIPTION
**Pull request by amueller**

### CODE REVIEW

**Comment by amueller** [comment]
Do you think there's anything else that's "urgent".
Damn, I wanted to run everything on python2, but didn't get to. Maybe we can do it quicker with nbconvert? not sure though.

**Comment by amueller** [comment]
why doesn't this have continuous integration? damn it!

**Comment by rasbt** [comment]
nothing urgent except Python 2 I think. That's actually tricky though, would have to look carefully for float integer division and that sort of stuff. Maybe people won't mind. E.g., we can say something like if someone gets different results, let us know, and then we fix it on a fly and sell it as an exercise or so ;)

**Comment by amueller** [comment]
ok, night time for me ;) see you tomorrow!

**Comment by rasbt** [comment]
allright. Glad we got everything done in time except these little things :P

**Comment by amueller** [comment]
well I'm sure we could spend another week on polishing it ;)

**Pull request merged**
